version: "3.8"
services:
  web_check:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_check
    image: web_check:latest
    volumes:
      - ./config.json:/web_check/config.json
      - ./url_list.json:/web_check/url_list.json
    environment:
      - TZ=Europe/Kyiv
    restart: always
