version: "3.8"
services:
  web_check:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_check
    image: web_check:latest
    volumes:
      - ./config.json:/web_check/config.json
      - ./url_list.json:/web_check/url_list.json
    environment:
      - TZ=UTC
    restart: always
    healthcheck:
      test: ["CMD", "pgrep", "-fl", "web_check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
