services:
  web_check:
    container_name: web_check
    image: ghcr.io/2boom-ua/web_check:latest
    network_mode: host
    volumes:
      - ./config.json:/web_check/config.json
      - ./url_list.json:/web_check/url_list.json
    environment:
      - TZ=Etc/UTC
    restart: always

